### ISSUE TITLE
Tailwind config

### ISSUE THREAD

**Issue by hemudi** [hemudi/hannip-form#5]
## 💬 Description
디자인 시스템 기반 공통 속성 및 기본 스타일 적용

## 📝 Todo
- [x] 공통 색상 추가
- [x] Pretendard 폰트 추가
- [x] custom font size 추가

## 🧩 ETC
![컬러가이드](https://github.com/user-attachments/assets/39b704f4-2ca6-4def-8453-429677560f35)
![타이포](https://github.com/user-attachments/assets/19ad64de-9a2b-4c86-8c15-66aea7a3d90e)
