### ISSUE TITLE
온보딩 페이지

### ISSUE THREAD

**Issue by hemudi** [hemudi/hannip-form#8]
## 💬 Description
온보딩 페이지를 구현

## 📝 Todo
- [x] 온보딩 페이지 Markup
  - [x] Slider 컴포넌트 구현
  - [ ] Slider Animation 추가
- [ ] 온보딩 이미지 추가

## 🧩 ETC
![스크린샷 2024-07-25 오후 9 51 38](https://github.com/user-attachments/assets/c793e64c-b4db-4d86-8003-650b5a3b352c)
⚠️ 디자인 미완
